status = [
    'linter-check',
    'phpstan-tests',

    'integration-tests (PHP 7.4) (Guzzle-7)',
    'integration-tests (PHP 7.4) (Guzzle-7-Adapter)',
    'integration-tests (PHP 7.4) (PHP-HTTP-CurlClient)',
    'integration-tests (PHP 7.4) (Kriswallsmith-Buzz)',

    'integration-tests (PHP 8.0) (Guzzle-7)',
    'integration-tests (PHP 8.0) (Guzzle-7-Adapter)',
    'integration-tests (PHP 8.0) (PHP-HTTP-CurlClient)',
    'integration-tests (PHP 8.0) (Kriswallsmith-Buzz)',

    'integration-tests (PHP 8.1) (Guzzle-7)',
    'integration-tests (PHP 8.1) (Guzzle-7-Adapter)',
    'integration-tests (PHP 8.1) (PHP-HTTP-CurlClient)',
    'integration-tests (PHP 8.1) (Kriswallsmith-Buzz)',

    'integration-tests (PHP 8.2) (Guzzle-7)',
    'integration-tests (PHP 8.2) (Guzzle-7-Adapter)',
    'integration-tests (PHP 8.2) (Symfony-HttpClient)',
    'integration-tests (PHP 8.2) (PHP-HTTP-CurlClient)',
    'integration-tests (PHP 8.2) (Kriswallsmith-Buzz)',

    'integration-tests (PHP 8.3) (Guzzle-7)',
    'integration-tests (PHP 8.3) (Guzzle-7-Adapter)',
    'integration-tests (PHP 8.3) (Symfony-HttpClient)',
    'integration-tests (PHP 8.3) (PHP-HTTP-CurlClient)',
    'integration-tests (PHP 8.3) (Kriswallsmith-Buzz)',
]
# 1 hour timeout
timeout-sec = 3600
