status = [
    'linter-check',
    'phpstan-tests',
    'integration-tests (PHP 7.3)',
    'integration-tests (PHP 7.4)',
    'integration-tests (PHP 8.0)',
    'integration-tests (PHP 8.1)'
]
# 1 hour timeout
timeout-sec = 3600
